import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import PageHeader from "@/components/page-header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Preview Profile Metrics",
  description: "Preview your GitHub profile metrics generated by Takumi.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PageHeader />
        <main className="p-4 px-28">{children}</main>
      </body>
    </html>
  );
}
