name: Generate LR Tech Blog Metrics

on:
  schedule: [{ cron: "0 0 * * 0" }]
  workflow_dispatch:

jobs:
  blog_metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Blog Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: blog_metrics.svg
          token: ${{ secrets.METRIC_TOKEN }}
          config_timezone: America/Fortaleza
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://lrtechblog.vercel.app
          plugin_pagespeed_screenshot: yes
          config_order: pagespeed

      - name: RSS Feed
        uses: lowlighter/metrics@latest
        with:
          filename: rss_feed.svg
          token: ${{ secrets.METRIC_TOKEN }}
          config_timezone: America/Fortaleza
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: LR-Tech-Blog/blog
          plugin_repositories_affiliations: organization_member
          plugin_rss: yes
          plugin_rss_source: https://lrtechblog.vercel.app/rss.xml
          plugin_rss_limit: 5
          config_order: repositories, rss
