name: Test Metrics

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: RetroAchievements
        uses: LuanRoger/metrics@0684b0b312519536133101106f61923426746e68
        with:
            filename: retroachievements.svg
            token: ${{ secrets.METRIC_TOKEN }}
            config_timezone: America/Fortaleza
            base: ""
            plugin_retroachievements: yes
            plugin_retroachievements_token: ${{ secrets.RETROACHIEVEMENTS_TOKEN }}
            plugin_retroachievements_username: TheROG
            plugin_retroachievements_target: TheROG
            plugin_retroachievements_showachievements: yes
            plugin_retroachievements_lastsin: 7
            plugin_retroachievements_achievementslimit: 3
